
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("3ecfa307-5d31-4945-b7a4-75cab770417a")>
Namespace NorthwindModel

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class NorthwindEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=NorthwindEntities", "NorthwindEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new NorthwindEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "NorthwindEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new NorthwindEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "NorthwindEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Invoices() As ObjectSet(Of Invoice)
            Get
                If (_Invoices Is Nothing) Then
                    _Invoices = MyBase.CreateObjectSet(Of Invoice)("Invoices")
                End If
                Return _Invoices
            End Get
        End Property
    
        Private _Invoices As ObjectSet(Of Invoice)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Invoices EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToInvoices(ByVal invoice As Invoice)
            MyBase.AddObject("Invoices", invoice)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Invoice")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Invoice
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Invoice object.
        ''' </summary>
        ''' <param name="customerName">Initial value of the CustomerName property.</param>
        ''' <param name="salesperson">Initial value of the Salesperson property.</param>
        ''' <param name="orderID">Initial value of the OrderID property.</param>
        ''' <param name="shipperName">Initial value of the ShipperName property.</param>
        ''' <param name="productID">Initial value of the ProductID property.</param>
        ''' <param name="productName">Initial value of the ProductName property.</param>
        ''' <param name="unitPrice">Initial value of the UnitPrice property.</param>
        ''' <param name="quantity">Initial value of the Quantity property.</param>
        ''' <param name="discount">Initial value of the Discount property.</param>
        Public Shared Function CreateInvoice(customerName As Global.System.String, salesperson As Global.System.String, orderID As Global.System.Int32, shipperName As Global.System.String, productID As Global.System.Int32, productName As Global.System.String, unitPrice As Global.System.Decimal, quantity As Global.System.Int16, discount As Global.System.Single) As Invoice
            Dim invoice as Invoice = New Invoice
            invoice.CustomerName = customerName
            invoice.Salesperson = salesperson
            invoice.OrderID = orderID
            invoice.ShipperName = shipperName
            invoice.ProductID = productID
            invoice.ProductName = productName
            invoice.UnitPrice = unitPrice
            invoice.Quantity = quantity
            invoice.Discount = discount
            Return invoice
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipName() As Global.System.String
            Get
                Return _ShipName
            End Get
            Set
                OnShipNameChanging(value)
                ReportPropertyChanging("ShipName")
                _ShipName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipName")
                OnShipNameChanged()
            End Set
        End Property
    
        Private _ShipName As Global.System.String
        Private Partial Sub OnShipNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipAddress() As Global.System.String
            Get
                Return _ShipAddress
            End Get
            Set
                OnShipAddressChanging(value)
                ReportPropertyChanging("ShipAddress")
                _ShipAddress = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipAddress")
                OnShipAddressChanged()
            End Set
        End Property
    
        Private _ShipAddress As Global.System.String
        Private Partial Sub OnShipAddressChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipAddressChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipCity() As Global.System.String
            Get
                Return _ShipCity
            End Get
            Set
                OnShipCityChanging(value)
                ReportPropertyChanging("ShipCity")
                _ShipCity = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipCity")
                OnShipCityChanged()
            End Set
        End Property
    
        Private _ShipCity As Global.System.String
        Private Partial Sub OnShipCityChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipCityChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipRegion() As Global.System.String
            Get
                Return _ShipRegion
            End Get
            Set
                OnShipRegionChanging(value)
                ReportPropertyChanging("ShipRegion")
                _ShipRegion = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipRegion")
                OnShipRegionChanged()
            End Set
        End Property
    
        Private _ShipRegion As Global.System.String
        Private Partial Sub OnShipRegionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipRegionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipPostalCode() As Global.System.String
            Get
                Return _ShipPostalCode
            End Get
            Set
                OnShipPostalCodeChanging(value)
                ReportPropertyChanging("ShipPostalCode")
                _ShipPostalCode = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipPostalCode")
                OnShipPostalCodeChanged()
            End Set
        End Property
    
        Private _ShipPostalCode As Global.System.String
        Private Partial Sub OnShipPostalCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipPostalCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShipCountry() As Global.System.String
            Get
                Return _ShipCountry
            End Get
            Set
                OnShipCountryChanging(value)
                ReportPropertyChanging("ShipCountry")
                _ShipCountry = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ShipCountry")
                OnShipCountryChanged()
            End Set
        End Property
    
        Private _ShipCountry As Global.System.String
        Private Partial Sub OnShipCountryChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipCountryChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property CustomerID() As Global.System.String
            Get
                Return _CustomerID
            End Get
            Set
                OnCustomerIDChanging(value)
                ReportPropertyChanging("CustomerID")
                _CustomerID = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("CustomerID")
                OnCustomerIDChanged()
            End Set
        End Property
    
        Private _CustomerID As Global.System.String
        Private Partial Sub OnCustomerIDChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCustomerIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CustomerName() As Global.System.String
            Get
                Return _CustomerName
            End Get
            Set
                If (_CustomerName <> Value) Then
                    OnCustomerNameChanging(value)
                    ReportPropertyChanging("CustomerName")
                    _CustomerName = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("CustomerName")
                    OnCustomerNameChanged()
                End If
            End Set
        End Property
    
        Private _CustomerName As Global.System.String
        Private Partial Sub OnCustomerNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCustomerNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Address() As Global.System.String
            Get
                Return _Address
            End Get
            Set
                OnAddressChanging(value)
                ReportPropertyChanging("Address")
                _Address = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Address")
                OnAddressChanged()
            End Set
        End Property
    
        Private _Address As Global.System.String
        Private Partial Sub OnAddressChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnAddressChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property City() As Global.System.String
            Get
                Return _City
            End Get
            Set
                OnCityChanging(value)
                ReportPropertyChanging("City")
                _City = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("City")
                OnCityChanged()
            End Set
        End Property
    
        Private _City As Global.System.String
        Private Partial Sub OnCityChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCityChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Region() As Global.System.String
            Get
                Return _Region
            End Get
            Set
                OnRegionChanging(value)
                ReportPropertyChanging("Region")
                _Region = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Region")
                OnRegionChanged()
            End Set
        End Property
    
        Private _Region As Global.System.String
        Private Partial Sub OnRegionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnRegionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property PostalCode() As Global.System.String
            Get
                Return _PostalCode
            End Get
            Set
                OnPostalCodeChanging(value)
                ReportPropertyChanging("PostalCode")
                _PostalCode = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("PostalCode")
                OnPostalCodeChanged()
            End Set
        End Property
    
        Private _PostalCode As Global.System.String
        Private Partial Sub OnPostalCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPostalCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Country() As Global.System.String
            Get
                Return _Country
            End Get
            Set
                OnCountryChanging(value)
                ReportPropertyChanging("Country")
                _Country = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Country")
                OnCountryChanged()
            End Set
        End Property
    
        Private _Country As Global.System.String
        Private Partial Sub OnCountryChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCountryChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Salesperson() As Global.System.String
            Get
                Return _Salesperson
            End Get
            Set
                If (_Salesperson <> Value) Then
                    OnSalespersonChanging(value)
                    ReportPropertyChanging("Salesperson")
                    _Salesperson = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("Salesperson")
                    OnSalespersonChanged()
                End If
            End Set
        End Property
    
        Private _Salesperson As Global.System.String
        Private Partial Sub OnSalespersonChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnSalespersonChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property OrderID() As Global.System.Int32
            Get
                Return _OrderID
            End Get
            Set
                If (_OrderID <> Value) Then
                    OnOrderIDChanging(value)
                    ReportPropertyChanging("OrderID")
                    _OrderID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrderID")
                    OnOrderIDChanged()
                End If
            End Set
        End Property
    
        Private _OrderID As Global.System.Int32
        Private Partial Sub OnOrderIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnOrderIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property OrderDate() As Nullable(Of Global.System.DateTime)
            Get
                Return _OrderDate
            End Get
            Set
                OnOrderDateChanging(value)
                ReportPropertyChanging("OrderDate")
                _OrderDate = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("OrderDate")
                OnOrderDateChanged()
            End Set
        End Property
    
        Private _OrderDate As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnOrderDateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnOrderDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property RequiredDate() As Nullable(Of Global.System.DateTime)
            Get
                Return _RequiredDate
            End Get
            Set
                OnRequiredDateChanging(value)
                ReportPropertyChanging("RequiredDate")
                _RequiredDate = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("RequiredDate")
                OnRequiredDateChanged()
            End Set
        End Property
    
        Private _RequiredDate As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnRequiredDateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnRequiredDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ShippedDate() As Nullable(Of Global.System.DateTime)
            Get
                Return _ShippedDate
            End Get
            Set
                OnShippedDateChanging(value)
                ReportPropertyChanging("ShippedDate")
                _ShippedDate = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ShippedDate")
                OnShippedDateChanged()
            End Set
        End Property
    
        Private _ShippedDate As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnShippedDateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnShippedDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ShipperName() As Global.System.String
            Get
                Return _ShipperName
            End Get
            Set
                If (_ShipperName <> Value) Then
                    OnShipperNameChanging(value)
                    ReportPropertyChanging("ShipperName")
                    _ShipperName = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("ShipperName")
                    OnShipperNameChanged()
                End If
            End Set
        End Property
    
        Private _ShipperName As Global.System.String
        Private Partial Sub OnShipperNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnShipperNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ProductID() As Global.System.Int32
            Get
                Return _ProductID
            End Get
            Set
                If (_ProductID <> Value) Then
                    OnProductIDChanging(value)
                    ReportPropertyChanging("ProductID")
                    _ProductID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("ProductID")
                    OnProductIDChanged()
                End If
            End Set
        End Property
    
        Private _ProductID As Global.System.Int32
        Private Partial Sub OnProductIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnProductIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ProductName() As Global.System.String
            Get
                Return _ProductName
            End Get
            Set
                If (_ProductName <> Value) Then
                    OnProductNameChanging(value)
                    ReportPropertyChanging("ProductName")
                    _ProductName = StructuralObject.SetValidValue(value, false)
                    ReportPropertyChanged("ProductName")
                    OnProductNameChanged()
                End If
            End Set
        End Property
    
        Private _ProductName As Global.System.String
        Private Partial Sub OnProductNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnProductNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property UnitPrice() As Global.System.Decimal
            Get
                Return _UnitPrice
            End Get
            Set
                If (_UnitPrice <> Value) Then
                    OnUnitPriceChanging(value)
                    ReportPropertyChanging("UnitPrice")
                    _UnitPrice = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("UnitPrice")
                    OnUnitPriceChanged()
                End If
            End Set
        End Property
    
        Private _UnitPrice As Global.System.Decimal
        Private Partial Sub OnUnitPriceChanging(value As Global.System.Decimal)
        End Sub
    
        Private Partial Sub OnUnitPriceChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Quantity() As Global.System.Int16
            Get
                Return _Quantity
            End Get
            Set
                If (_Quantity <> Value) Then
                    OnQuantityChanging(value)
                    ReportPropertyChanging("Quantity")
                    _Quantity = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Quantity")
                    OnQuantityChanged()
                End If
            End Set
        End Property
    
        Private _Quantity As Global.System.Int16
        Private Partial Sub OnQuantityChanging(value As Global.System.Int16)
        End Sub
    
        Private Partial Sub OnQuantityChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Discount() As Global.System.Single
            Get
                Return _Discount
            End Get
            Set
                If (_Discount <> Value) Then
                    OnDiscountChanging(value)
                    ReportPropertyChanging("Discount")
                    _Discount = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Discount")
                    OnDiscountChanged()
                End If
            End Set
        End Property
    
        Private _Discount As Global.System.Single
        Private Partial Sub OnDiscountChanging(value As Global.System.Single)
        End Sub
    
        Private Partial Sub OnDiscountChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ExtendedPrice() As Nullable(Of Global.System.Decimal)
            Get
                Return _ExtendedPrice
            End Get
            Set
                OnExtendedPriceChanging(value)
                ReportPropertyChanging("ExtendedPrice")
                _ExtendedPrice = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ExtendedPrice")
                OnExtendedPriceChanged()
            End Set
        End Property
    
        Private _ExtendedPrice As Nullable(Of Global.System.Decimal)
        Private Partial Sub OnExtendedPriceChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub OnExtendedPriceChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Freight() As Nullable(Of Global.System.Decimal)
            Get
                Return _Freight
            End Get
            Set
                OnFreightChanging(value)
                ReportPropertyChanging("Freight")
                _Freight = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Freight")
                OnFreightChanged()
            End Set
        End Property
    
        Private _Freight As Nullable(Of Global.System.Decimal)
        Private Partial Sub OnFreightChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub OnFreightChanged()
        End Sub

        #End Region

    End Class

    #End Region

    
End Namespace
